### ISSUE TITLE
Warning: React does not recognize the `rawContent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `rawcontent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by NellyHaglund** [josephj/react-icalendar-link#16] opened 2021-07-29 08:37 UTC
Using ICalendarLink causing **warning** when used with React. Happening both when `rawContent` prop is passed, and when it is not.
```
import ICalendarLink from 'react-icalendar-link';

<ICalendarLink event={event}>
     Add to Calendar
</ICalendarLink>

```

```
Warning: React does not recognize the `rawContent` prop on a DOM element.
If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `rawcontent` instead.
If you accidentally passed it from a parent component, remove it from the DOM element.
 at a
    at ICalLink
```

**Comment by andrewMuntyan** [comment] 2021-08-24 16:27
Same issue here. this is duplicate of #15

**Comment by josephj** [comment] 2021-11-06 20:24
Fixed

**Closed** 2021-11-06 20:27 UTC
